{"uuid": "4d4ae434-cd12-47af-b58e-71ee4b728eb1", "children": ["0a5f3793-797a-467b-b6d7-644d688bb3b9"], "befores": [{"name": "open_url", "status": "passed", "start": 1601432548645, "stop": 1601432548645}], "afters": [{"name": "open_url::0", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=85.0.4183.121)\n\n", "trace": "  File \"E:\\Program Files\\Python\\Python38\\lib\\site-packages\\allure_commons\\_allure.py\", line 185, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"E:\\Program Files\\Python\\Python38\\lib\\site-packages\\_pytest\\fixtures.py\", line 932, in _teardown_yield_fixture\n    next(it)\n  File \"D:\\PytestAutoTestFrameWork-master\\TestCases\\conftest.py\", line 57, in open_url\n    driver.delete_all_cookies()\n  File \"E:\\Program Files\\Python\\Python38\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 878, in delete_all_cookies\n    self.execute(Command.DELETE_ALL_COOKIES)\n  File \"E:\\Program Files\\Python\\Python38\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"E:\\Program Files\\Python\\Python38\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1601432551415, "stop": 1601432551447}], "start": 1601432548645, "stop": 1601432551447}